### ISSUE TITLE
Automatically apply updates regularly

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#102]
Right now, we manually apply updates on the linux boxes (the macs are set to auto-update). We should add a cron job or similar to auto-update the linux boxes.

**Comment by metajack** [comment]
@edunham What is the standard way of doing this? A cron job would work, but this seems so basic that there must be some better way.

**Comment by edunham** [comment]
Cron is the right solution for running a task on a fixed schedule, so few
config management tools reinvent it.

Salt should differentiate between a package's latest version and some
specific version. We could run a salt state through cron to update those
packages which should be latest without accidentally updating anything
which needs a set version.

**Comment by aneeshusa** [comment]
Salt has separate pkg.latest and pkg.installed states, so if you know which packages should be updated it's possible to change those to pkg.latest and version pin the rest. Then, running state.highstate again will run the necessary updates, and that can be done from cron or manually.

**Comment by larsbergstrom** [comment]
Better info in #275
