### ISSUE TITLE
buildbot-master needs python3

### ISSUE THREAD

**Issue by Manishearth** [servo/saltfs#142]
Homu only works on a python3 toolchain. Our salt configuration does not autoinstall this.

Homu worked so far because it somehow had a python3 virtualenv with everything it needed, without a global install of any of the python3 tools.

Specifically, we need:

```
sudo apt-get install python3.4 python3-pip
pip3 install virtualenv
```

We can do the former with a `- require: - pkg: ` key in `homu.sls` somewhere.

I'm not sure how to indicate a pip3-specific dependency, though. Perhaps something with `bin_env`?

We also need to make sure that the pip/python/virtualenv setup does not make 3.4 the default for the `pip`/`python`/`virtualenv` binaries. Installing them as shown above seemed to preserve the default, but I'm not sure if that's something we can rely on.

cc @edunham @larsbergstrom

**Comment by edunham** [comment]
We might run into https://github.com/saltstack/salt/issues/5494 with Salt. One workaround would be to create the virtualenv, with the flags telling it to use python3, through a shell command.

**Comment by Manishearth** [comment]
Huh. It worked for us, the current salt configuration just says "virtualenv.managed, but use the binary called `virtualenv3.4`" and it works
