### ISSUE TITLE
Wiki/Docs for contributing

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#151]
The current README says to check the wiki for information on tutorials and contributing, but it looks like the wiki has been disabled. I have a few things I'd like to write up (such as how to use Vagrant, how to invoke Salt, etc.) so can the wiki be re-enabled? Alternately, I can start a CONTRIBUTING file, but I'm worried it will get longer and harder to navigate over time.

**Comment by Manishearth** [comment]
We usually keep everything on the main wiki, e.g. https://github.com/servo/servo/wiki/Buildbot-administration

**Comment by aneeshusa** [comment]
OK, sounds good! The making changes directly on servo-master.servo.org has me slightly worried :stuck_out_tongue_winking_eye:, but I'll see what I can do about updating the docs.
