### ISSUE TITLE
Buildmaster API needs a password

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#172]
Could be possible to trigger arbitrary builds right now.

**Comment by metajack** [comment]
It has one I'm pretty sure. Check the config and secrets file.

**Comment by Manishearth** [comment]
The force build button is still visible here without being logged in. http://build.servo.org/builders/linux-rel

**Comment by edunham** [comment]
OK, now that that's deployed... Saying 'True' rather than 'auth' for all actions meant anybody could force and kill builds, regardless of login status. @metajack was correct that a password was set, but the prior config missed the step of testing whether or not the user was authed before allowing all actions.
