### ISSUE TITLE
Travis broken due to version issue

### ISSUE THREAD

**Issue by Manishearth** [servo/saltfs#174]
https://travis-ci.org/servo/saltfs/jobs/96681145

```
E: Version '2015.5.6+ds-1' for 'salt-minion' was not found
```

cc @aneeshusa

**Comment by aneeshusa** [comment]
I was actually planning to move to 2015.8 soon (i.e. #165) but it looks like 2015.5 has been updated in the meantime. I'll put in a PR today to bump the minor version for now to get CI working again.

Also, it looks like they are now keeping archives of previous versions on their repository with the newest update (something I was waiting for [https://github.com/saltstack/salt/issues/29098]), so we shouldn't see this issue again.
