### ISSUE TITLE
servo-linux1 machine

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#185]
It looks like [it's been removed from the wiki](https://github.com/servo/servo/wiki/Buildbot-administration/_compare/8dfa5da15248a2a2da7b60702b7729085ab69e42); is this machine no longer being used? If so, it should be cleared from the .travis.yml and top.sls files, and the wiki should be updated to not use it as an example.

cc @larsbergstrom (since you made the wiki edit)

**Comment by larsbergstrom** [comment]
@aneeshusa Yes! With the move to EC2, it has been reclaimed. Will do.
