### ISSUE TITLE
Problems with setting up the msttfonts on linux

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#186]
We moved EC2 builders this past week, and had problems with the MS TT fonts installer again. The relevant install lines appear to be here:
https://github.com/servo/saltfs/blob/master/servo-dependencies.sls#L10-L19

What seems to have happened (from looking at the failing machine) is that the mscorefonts-eula was set to `False` rather than true before the installation of the package happened, and so the package was showing as installed but none of the fonts were available. I had to reset the eula flag then forcibly uninstall/reinstall the fonts.

Any ideas? CC: @metajack @aneeshusa @edunham

**Comment by aneeshusa** [comment]
How can I tell if the fonts are properly installed? I checked it out in a Vagrant VM and it seems to work OK: the fonts are getting downloaded and placed into /usr/share/fonts/truetype/msttcorefonts, and it looks like the debconf selection is getting set properly.

**Comment by metajack** [comment]
When it fails nothing is created in /usr/share/fonts/truetype but no errors are reported and the debconf selections are all fine. You can look at the salt log in AWS boot or on the build machines for its details, but not much is reported there other than it successfully installed the package.

**Comment by aneeshusa** [comment]
Hmm, interesting. I thinking looking at the logs will be important to figure this one out, but I don't want to just put them in a Gist or Pastebin. Would you be comfortable giving me SSH access to these machines? Also, which machines (hostnames) had this problem?

**Comment by larsbergstrom** [comment]
Sure! I'd be happy to give you access to ssh in. You can open a PR like https://github.com/servo/saltfs/pull/184 to try it out.

IIRC, it happened to our EC2 "linux2" builder. I can give you that IP after we have your ssh key installed. Alternatively, I can also log in there and retrieve any logs that you need.

**Comment by larsbergstrom** [comment]
Also, if it matters, I've noticed that if I `highstate` that box, I sometimes get:
```
----------
          ID: FIX enable multiverse
    Function: pkgrepo.absent
        Name: deb http://archive.ubuntu.com/ubuntu trusty multiverse
      Result: True
     Comment: Removed package repo deb http://archive.ubuntu.com/ubuntu trusty multiverse
     Started: 13:09:30.857022
    Duration: 6125.226 ms
     Changes:   
              ----------
              repo:
                  deb http://archive.ubuntu.com/ubuntu trusty multiverse
----------
          ID: enable multiverse
    Function: pkgrepo.managed
        Name: deb http://archive.ubuntu.com/ubuntu trusty multiverse
      Result: True
     Comment: Configured package repo 'deb http://archive.ubuntu.com/ubuntu trusty multiverse'
     Started: 13:09:36.982359
    Duration: 2987.726 ms
     Changes:   
              ----------
              repo:
                  deb http://archive.ubuntu.com/ubuntu trusty multiverse
----------
```

**Comment by aneeshusa** [comment]
@larsbergstrom @edunham Did you run into this when setting up the new cross builders? Also, do you know if that was before or after #250 landed? If you didn't hit any problems this time, I think we can close this issue for now.

**Comment by larsbergstrom** [comment]
Confirmed that both of the cross builders provisioned with correctly-installed fonts. Thanks!
