### ISSUE TITLE
build.servo.org TLS not working

### ISSUE THREAD

**Issue by metajack** [servo/saltfs#196]
Firefox shows it as insecure

cc @edunham

**Comment by aneeshusa** [comment]
Did this ever work? The nginx config in `nginx/default` has only ever listened on port 80, without `ssl on`.

**Comment by edunham** [comment]
Cloudflare (account credentials are with the salt pillar backup) isn't currently enabled for build.servo.org. In other words, we've never had HTTPS on the buildbot instance. Turning cloudflare on would encrypt from the CDN to the end user but with the current setup, traffic would still be non-encrypted from Buildbot to the CDN. 

I'll also get to this in going through the security team's infrastructure assessment, but if we want to encrypt traffic to the buildmaster, we can get it a cert from Let's Encrypt.

**Comment by edunham** [comment]
Closing in favor of #423 since it got edited to add this as one of the steps required for completion
