### ISSUE TITLE
The new ssh key stuff doesn't handle using Administrator on the macs

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#208]
I think this patch did not work:
https://github.com/servo/saltfs/commit/c2ae361d98efcb2812c9f89ba36dc1d7d375eb34

CC @aneeshusa 

The root user on the macs is Administrator,.

**Comment by aneeshusa** [comment]
What isn't working about them? My SSH key was only added to this repo recently but I'm able to login to the Macs, and my ssh key shows up in the /var/root/.ssh/authorized_keys file.

**Comment by larsbergstrom** [comment]
@aneeshusa 

Aha! How curious - I can ssh in as `root@` to the macs now. Before this, I'd always been logging in as `administrator@`. So, I think this works fine, I just need to learn to use the root account instead of administrator to log in.

**Comment by larsbergstrom** [comment]
I've updated https://github.com/mozilla/servo/wiki/Buildbot-administration to mention that you should log in as `root`, not `administrator` to the OSX boxes now.
