### ISSUE TITLE
Need to `brew link --force openssl` on OSX

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#210]

**Comment by aneeshusa** [comment]
Oops, I didn't read very carefully and thought this was for autoconf, accidentally set this to close once #211 is merged.

**Comment by larsbergstrom** [comment]
I removed the closes line from the other PR :-)

**Comment by aneeshusa** [comment]
Well, I also put a closes line in the commit message. Yay for thoroughness?
