### ISSUE TITLE
Run new test-compiletest harness on builders

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#216]
Currently we only run on travis, so our merges don't gate on the testsuite passing.

**Comment by jdm** [comment]
This bit us when we removed a rustc plugin but not the corresponding unit tests :(

**Comment by aneeshusa** [comment]
Which platforms do we need to run this on/is this platform agnostic? For example, can we run this only on the `linux-dev` builder, or should we be running this on all platforms - development, release, ARM, OS X, etc?

**Comment by jdm** [comment]
Linux-dev should be enough.
