### ISSUE TITLE
Helps on the build issue on Mac OS X 

### ISSUE THREAD

**Issue by 2015xli** [servo/saltfs#221]
### I searched in the issue list, and it was suggested to be autoconf linking problem and that issue was closed. Tried to follow the suggestion there (https://github.com/servo/servo/issues/9504), did not succeed. Don't know if it is the same problem or not. Helps are appreciated.
# 

cd /Users/xli/GoogleDrive/2015xli@gmail.com/temp/git/servo/target/release/build/harfbuzz-sys-14497f51d6b45da3/out && make -j8
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in hb-ucdn
  CC       libhb_ucdn_la-ucdn.lo
  CCLD     libhb-ucdn.la
  CXX      libharfbuzz_la-hb-blob.lo
  CXX      libharfbuzz_la-hb-buffer-serialize.lo
  CXX      libharfbuzz_la-hb-buffer.lo
  CXX      libharfbuzz_la-hb-common.lo
  CXX      libharfbuzz_la-hb-face.lo
  CXX      libharfbuzz_la-hb-font.lo
  CXX      libharfbuzz_la-hb-ot-tag.lo
  CXX      libharfbuzz_la-hb-set.lo
  CXX      libharfbuzz_la-hb-shape.lo
  CXX      libharfbuzz_la-hb-shape-plan.lo
  CXX      libharfbuzz_la-hb-shaper.lo
  CXX      libharfbuzz_la-hb-unicode.lo
  CXX      libharfbuzz_la-hb-warning.lo
  CXX      libharfbuzz_la-hb-ot-font.lo
  CXX      libharfbuzz_la-hb-ot-layout.lo
  CXX      libharfbuzz_la-hb-ot-map.lo
  CXX      libharfbuzz_la-hb-ot-shape.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-arabic.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-default.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-hangul.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-hebrew.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-indic.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-indic-table.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-myanmar.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-thai.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-tibetan.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-use.lo
  CXX      libharfbuzz_la-hb-ot-shape-complex-use-table.lo
  CXX      libharfbuzz_la-hb-ot-shape-normalize.lo
  CXX      libharfbuzz_la-hb-ot-shape-fallback.lo
  CXX      libharfbuzz_la-hb-fallback-shape.lo
  CXX      libharfbuzz_la-hb-ucdn.lo
  CXX      main-main.o
  CXX      test-test.o
  CXX      test_buffer_serialize-test-buffer-serialize.o
  CXX      test_size_params-test-size-params.o
  CXX      test_would_substitute-test-would-substitute.o
  GEN      harfbuzz.pc

--- stderr
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.15 is not found.
make[1]: warning: -jN forced in submake: disabling jobserver mode.
sed: 1: "s@%prefix%@/Users/xli/G ...": bad flag in substitute command: 'm'
/bin/sh: harfbuzz.pc: command not found
make[5]: **\* [harfbuzz.pc] Error 1
make[5]: **\* Waiting for unfinished jobs....
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [all-recursive] Error 1
make[1]: **\* [all] Error 2
make: **\* [all] Error 2
thread '<main>' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env:: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', /Users/xli/GoogleDrive/xiaofeng.li@gmail.com/temp/git/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/harfbuzz-sys-0.1.2/build.rs:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build completed in 122.83s

**Comment by jdm** [comment]
@nhirata suggested in #9612 that `brew install gtk-doc` will solve this.

**Comment by paulrouget** [comment]
> @nhirata suggested in servo/servo#9612 that brew install gtk-doc will solve this.

That's surprising.

Maybe it's the missing `autoheader` issue.

@2015xli any error about autoconf and/or autoheader?

**Comment by 2015xli** [comment]
Thanks for the helps. I am continuing to check the problem, and will update the progress here. 

@jdm  gtk-doc does not help my case.

@paulrouget It may be related to autoconf/autoheader. I have not identified the root cause yet.

**Comment by nhirata** [comment]
FYI, I was able to compile in my case.  I had the same error : 
"You will not be able to create source packages with 'make dist' because gtk-doc >= 1.15 is not found."

see: https://github.com/servo/servo/issues/9612

**Comment by nhirata** [comment]
Oh.  I did want to mention after installing both, I did have to fix my autoconf link.  I had to relink my autoconf doing a little search for autoconf and the link it was looking for and relinking it with brew.

**Comment by edunham** [comment]
@2015xli Are you still having this problem? The saltfs issue queue is generally for problems with the build infrastructure that Servo runs, whereas the servo/servo repo's issues include user support. You might be able to follow out buildslave installation steps and use Salt to configure a Mac to look the same as the environments where we test Servo, but that doesn't seem to be the question at hand.

**Comment by edunham** [comment]
Actually, the better way to do this is to close this bug and ask you nicely to re-open it with clarification if it is still a problem. So, if this is still a problem, could you please reopen this bug and clarify what you would like us to do to help you? Thanks!

**Comment by 2015xli** [comment]
Thanks!

--
Xiao-Feng Li
VP of Engineering, General manager (USA),
HUAMI Inc.

2485 Old Middlefield Way, Suite 30, Mountain View, CA 94043
