### ISSUE TITLE
Vagrant on Linux failing to load due to permission error with the minon file?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#238]
@aneeshusa Do you have any idea why this might be failing when I attempt to `vagrant up` a new machine and how to fix it?

```
Copying salt minion config to /etc/salt
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /home/larsberg/saltfs/.travis/minion
Dest: /etc/salt/minion
[larsberg@thor saltfs]$ 
```

**Comment by larsbergstrom** [comment]
Aha! Looks like this is a problem with newer Vagrants:
https://github.com/mitchellh/vagrant/issues/5973

**Comment by larsbergstrom** [comment]
s/newer/older. Ubuntu installs 1.7.4 Vagrant, but #180 moved us to 1.8.0. So this is user error on my part!

**Comment by aneeshusa** [comment]
Thanks for updating the wiki, I totally meant to add that after the PR landed but forgot! This bug was definitely a thorn in the side for a while.

**Comment by larsbergstrom** [comment]
No problem! It was actually somewhat fortunate, as I wasn't in a huge rush today and it forced me to learn a lot about how Vagrant works :-)
