### ISSUE TITLE
Investigations of failures to provision the ARM cross builders

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#280]
As noted in #274, we are failing to install the ubuntu packages 'g++-arm-linux-gnueabihf' & 'g++-aarch64-linux-gnu' in GCE.

Just now, I did an `apt-get upgrade` on the cross builders (as I noticed that they had failed to autoupdate) and got:
```
root@ip-172-31-34-111:~# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 libstdc++-4.8-dev-armhf-cross : Depends: libstdc++6-armhf-cross (>= 4.8.4-2ubuntu1~14.04.1cross0.11.1) but 4.8.2-16ubuntu4cross0.11 is installed
 libstdc++6-armhf-cross : Depends: gcc-4.8-arm-linux-gnueabihf-base (= 4.8.2-16ubuntu4cross0.11) but 4.8.4-2ubuntu1~14.04.1cross0.11.1 is installed
E: Unmet dependencies. Try using -f.
root@ip-172-31-34-111:~# 
```

**Comment by larsbergstrom** [comment]
cc @edunham @aneeshusa

**Comment by aneeshusa** [comment]
It's a known packaging bug: https://bugs.launchpad.net/ubuntu/+source/gcc-4.8-armhf-cross/+bug/1557205

Running the following appears to be the recommended temporary solution:
```
sudo apt-get -o Dpkg::Options::="--force-overwrite" install -f
```

We can do this on the builders if we need to, but this would require some hackery to add to Travis. From what I understand from a Vagrant session we'd need to try installing and then run the command to fix the packages; least hacky way would be editing our `.travis.yml` to add a conditional to install and run the fix on the cross builder before running the highstate.

I'd like to avoid doing this if possible, but if it's a priority I can put in a PR. (I'm hoping this gets fixed upstream quickly.)

**Comment by larsbergstrom** [comment]
@edunham and I chatted and we agree to just wait for upstream to fix it.

The main thing in the meantime is that we have to check the travis log failures carefully by hand.
