### ISSUE TITLE
Don't hard-code /etc/hosts entries

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#287]
The `common/init.sls` file adds a lot of entries to `/etc/hosts`. We should use DNS for name resolution instead.

@edunham reminded me of this by mentioning 'messy hacks around not trusting DNS' in IRC, so if there are any other hacks we should get rid of those too.

**Comment by larsbergstrom** [comment]
Yeah, @edunham ran into this during the move.

I think those predate her (awesome) move of us to CloudFlare and DNS self-management. It used to take a couple of days to get a DNS entry changed via internal corporate IT DNS management, so that's clearly not needed anymore :-)

**Comment by aneeshusa** [comment]
I can't read my IRC client, it was @edunham that mentioned it! My apologies.

Did you run into any other issues during the move?

**Comment by aneeshusa** [comment]
Closing in favor of #288.
