### ISSUE TITLE
Remove hardcoded IPs

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#288]
Follow-up from discussion in https://github.com/servo/saltfs/issues/281 . 

We have a bunch of IPs hardcoded into `common/map.jinja`. This was useful when we had to manage DNS through Mozilla support tickets, but we control everything directly through CloudFlare now. 

Todo: 
- [ ] Remove the IPs from map.jinja
- [ ] Remove the states which add the IPs to the hosts file
- [ ] Test everything in Vagrant
- [ ] Deploy changes to one buildslave, see if it still connects and runs builds successfully

**Comment by edunham** [comment]
Duplicate of https://github.com/servo/saltfs/issues/287

**Comment by aneeshusa** [comment]
This is clearer and has better instructions than the other issue I opened, so closing it in favor of reopening this one.

**Comment by setupminimal** [comment]
Hi! I'm looking to contribute to Servo, and this was mentioned on Servo Starters, so I'm going to try it. Thanks!

**Comment by aneeshusa** [comment]
@setupminimal It's yours, let us know if you have any questions!

**Comment by tictakk** [comment]
Hey I'm a little confused, is this still an issue? Is this still assigned?

**Comment by aneeshusa** [comment]
This actually got taken care of in https://github.com/servo/saltfs/pull/577/commits/95ab185a7be4cc5f245ea2c925ecf7185c0cf84a already, thanks for checking!
