### ISSUE TITLE
Something still wrong with our rust-bindgen setup

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#306]
When I attempt to hit synchronize on http://build.servo.org/homu/queue/rust-bindgen, I get:

```
Error: 400 Bad Request

Sorry, the requested URL 'http://build.servo.org:54856/callback?code=cd3940d0b43e37212ce1&state=%7B%22cmd%22%3A%22synch%22%2C%22repo_label%22%3A%22rust-bindgen%22%7D' caused an error:

You are not a collaborator
```

I'm pretty sure that they added bors-servo as a collaborator, though! I'm one, too. Hrm, this is confusing...

cc @nox

**Comment by larsbergstrom** [comment]
This is for the repository https://github.com/crabtw/rust-bindgen

**Comment by edunham** [comment]
@crabtw could you confirm that @bors-servo has write or admin permissions on your rust-bindgen repo?

**Comment by Manishearth** [comment]
It needs more than that, it needs access to the push/comment/status webhooks iirc

**Comment by crabtw** [comment]
@edunham bors-servo is in the collaborator list so it should have write permission.

**Comment by larsbergstrom** [comment]
Hrm, I'm still getting:

```
Error: 400 Bad Request

Sorry, the requested URL 'http://build.servo.org:54856/callback?code=e442be0cdbcc03397f86&state=%7B%22cmd%22%3A%22synch%22%2C%22repo_label%22%3A%22rust-bindgen%22%7D' caused an error:

You are not a collaborator
```

@crabtw I really apologize for how long this has taken me to configure! This is the first time we've set up our homu instance to work with a repository that is not in a GitHub organization.

**Comment by nox** [comment]
I think this was fixed, given rust-bindgen moved to the servo organisation.
