### ISSUE TITLE
Need automation for prebuilding Rust compiler

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#32]
In order to do a Servo release, we prebuild the Rust compiler. This is currently done on @larsbergstrom's laptop. 
Some relatively up-to-date docs on the prebuild process are at https://github.com/servo/servo/wiki/Updating-the-Rust-compiler-used-by-Servo

The machine which successfully builds the compiler is Ubuntu 14.04 LTS with installed software as described by the dpkg list at https://pastebin.mozilla.org/8835186

A better solution will be to have Salt configs describing a machine capable of building the compiler, which could be applied to a VM on one's laptop or to an EC2 instance.

**Comment by Manishearth** [comment]
Is there any specific setup for osx?

**Comment by larsbergstrom** [comment]
@Manishearth There's nothing at all interesting about the OSX setup except that it has the Android tools installed, which we don't have a builder for right now (because it wasn't working until ~2 weeks ago).

**Comment by edunham** [comment]
I'm using Ansible for the Rust infrastructure. The role which resolves this issue on the Linux side (still working on the OSX side) is currently [here](https://github.com/edunham/ansible-rust-infra/tree/master/roles/servo-compiler) though it may make more sense to factor it into its own repo later. 

In a clone of the repo linked above, I can `vagrant up ndk` (that's what I nicknamed the box that does the android cross-compiler build) and an Ubuntu 12.04 VM gets provisioned and builds the compiler described by the wiki page. Haven't rigorously tested that the built compiler behaves identically to the old one yet.

**Comment by edunham** [comment]
@Manishearth The mac just needs the packages required for building rust and [building the NDK](https://github.com/servo/servo/wiki/Building-for-Android), so it needs to have Brew installed. After the dependencies are installed, the commands for building the snapshot are the same as on Linux.

**Comment by larsbergstrom** [comment]
All done now! We are using the Rust nightly builds.
