### ISSUE TITLE
Build machines should purge .servo and .cargo directories occasionally

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#321]
Right now, we cache all rust/cargo binaries and cargo packages for _all_ time. This will eventually be a bad thing :-)

**Comment by edunham** [comment]
@larsbergstrom AIUI, https://github.com/servo/servo/issues/16487 addresses this issue. Could you update to reflect any further work you had in mind beyond that cleanout?

**Comment by aneeshusa** [comment]
That PR (`./mach clean-nightlies`) only cleans the `.servo` directory; servo/servo#16593 (`./mach clean-cargo-cache`) cleans the `.cargo` directory. `./mach clean-nightlies` is currently run on Travis and BuildBot, but `./mach clean-cargo-cache` is currently only run on Travis.

The remaining action item here is to run `./mach clean-cargo-cache` on Buildbot as well.

**Comment by cmac4603** [comment]
I can pick this up

**Comment by jdm** [comment]
Please do!

**Comment by tigercosmos** [comment]
PR open in servo/servo#19713

**Comment by tigercosmos** [comment]
Since servo/servo#19713 is merged.
This should be closed.
cc @aneeshusa @jdm
