### ISSUE TITLE
make sure servo user has perms on files needed to start buildbot

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#332]
if buildbot is ever erroneously started as root, it clobbers the perms on a bunch of files (twistd.log, events_build.servo.org/state, etc) that servo user needs access to in order to successfully start buildbot. it'd be nice if a highstate restored the correct perms. 

a `chown -R servo:servo /home/servo/buildbot` does the trick.

**Comment by aneeshusa** [comment]
What command did you use to start buildbot as root? I'd rather make it impossible to do so by checking the UID.

I'll make a PR to ensure the whole directory is owned by servo:servo.
