### ISSUE TITLE
Allow ICMP packets

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#336]
Currently, the (AWS?) firewall settings disallow ICMP packets, which makes us bad network citizens. ICMP is useful not only for debugging (ping, traceroute), but is also necessary for features such as path MTU discovery, and blocking ICMP doesn't add any security since we list these IP addresses in DNS anyways.

I would still recommend ICMP rate-limiting to prevent reflection attacks, if it's not too complicated to set up.

cc @edunham

**Comment by edunham** [comment]
@larsbergstrom I've moved all slaves to the 'default' group, deleted the spurious 'launch-wizard-x' groups, and allowed ICMP on the default and servo-master groups. When creating new slaves, please put them in the 'default' security group rather than creating a new one.

**Comment by larsbergstrom** [comment]
@edunham Thanks, will do!
