### ISSUE TITLE
buildbot steps need description and descriptionDone

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#337]
Waterfall currently just says "test" on all test steps. It would be better to have a short description of each step, or even just the full text of the command for that step. 

Buildbot docs at http://docs.buildbot.net/latest/manual/cfg-buildsteps.html#common-parameters describe `description` and `descriptionDone`, and [here](https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#L1064) is an example of them in use. 

Steps are created [here](https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/factories.py#L86) with configs drawn from [here](https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/steps.yml). 

@aneeshusa, what's your opinion on whether this should be implemented by adding the information to the yaml file or by inferring it from the commands?

**Comment by aneeshusa** [comment]
I want to keep the YAML file as simple as possible, so I'd say these should be generated from the commands. Given a shell command such as `./mach build --dev`, we can use `Running './mach build --dev'` for the `description`, and simply `./mach build --dev` for `descriptionDone`.

I think this could be added to `make_step` fairly easily.

**Comment by aneeshusa** [comment]
For `description`, we could also have this change based on the `Step` class: `Compiling`, `Testing`, `Running`, and not include the command as the docs say to keep the `description` field as a single imperfect-tense verb.

**Comment by UK992** [comment]
I want to claim this

**Comment by KiChjang** [comment]
@UK992 It's yours!
