### ISSUE TITLE
vagrant up failed

### ISSUE THREAD

**Issue by shinglyu** [servo/saltfs#344]
I tried to run `vagrant up`, but it failed with this error message:

https://gist.github.com/shinglyu/94732d6b7f6535a526db87dc8fa517cb#file-vagrant-log-L49

I'm trying to fix #325, not sure if I can do that without a full vagrant environment?

ping @edunham

**Comment by aneeshusa** [comment]
@shinglyu This is a bug I introduced; the fix is #298.

**Comment by aneeshusa** [comment]
To fix it temporarily, change `salt.bootstrap_script = '.travis/install_salt'` to `salt.bootstrap_script = '.travis/install_salt.sh'`.

**Comment by shinglyu** [comment]
Thanks!

**Comment by aneeshusa** [comment]
Closing because #298 has landed.
