### ISSUE TITLE
Run pkill on the Windows builders

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#351]
Our Linux and OS X builders [use pkill](https://github.com/servo/saltfs/blob/15d495985f3d255145740c1f40d4bebeacf3d712/buildbot/master/files/config/factories.py#L70
) before each build to ensure there are no extra `servo` processes.

We should also run this on the Windows builders. The best way to do this would be to write a custom script in the `etc/ci` directory of the main servo repository, which runs pkill on Linux/OS X, or the corresponding command on Windows (possibly `taskkill /im servo.exe`, see [this comment](https://github.com/servo/saltfs/pull/325#issuecomment-211637802)).

A possible complication is that we run Windows commands inside a [bash shell](https://github.com/servo/saltfs/blob/15d495985f3d255145740c1f40d4bebeacf3d712/buildbot/master/files/config/factories.py#L118); this script should either work from inside that shell, or be run outside of it.

**Comment by retep998** [comment]
You know what else you could do? Use job objects. Rust uses job objects to very good effect on its builders, and they ensure that there are no child processes of any sort hanging around.

**Comment by aneeshusa** [comment]
Do you have a doc link for job objects? Are they similar to control groups on Linux? (I've love to use process/control groups for much better control, but that will take some time to investigate, and I'm not sure about an equivalent for OS X.)

**Comment by retep998** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684161(v=vs.85).aspx

**Comment by aneeshusa** [comment]
Fixed in #426 using `powershell kill -n servo`.
