### ISSUE TITLE
Hook up this repo to highfive

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#353]
Add a webhook pointing at `http://www.joshmatthews.net/highfive/newpr.py`. See https://github.com/servo/highfive/pull/109#issuecomment-216412097.

**Comment by larsbergstrom** [comment]
I *think* I did it correctly - we'll see on the next PR open by somebody new!

**Comment by aneeshusa** [comment]
I don't think this is set up properly - see #359 where highfive didn't leave a comment.

**Comment by jdm** [comment]
We may need a Robots team like the main servo repo does.

**Comment by aneeshusa** [comment]
Should be fixed now: http://logs.glob.uno/?c=mozilla%23servo#c422225

**Comment by aneeshusa** [comment]
Apparently still not fixed - Highfive didn't leave a comment on #369, either.

**Comment by aneeshusa** [comment]
Looks like this is working as of #499, will close this after 1/2 more PRs to verify.

**Comment by larsbergstrom** [comment]
FYI, @jdm was right - the Robots group did not have write access to the repo. After adding that this Friday, it seems to be working.

**Comment by aneeshusa** [comment]
Ah ok, in that case since it didn't just spontaneously start working, this should be good to go.
