### ISSUE TITLE
Windows builder is not caching cargo and rust deps

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#358]
Need to set the `CARGO_HOME` and `SERVO_CACHE_DIR` environment variables to something sensible to avoid wasting a *ton* of time on our Windows builder.

Changes should be made to this file:
https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/environments.py

**Comment by aneeshusa** [comment]
Specifically, these variables should be added to the `build_windows` expression.

**Comment by jeandudey** [comment]
What about using `%APPDATA%\.cargo` for `CARGO_HOME` and `%APPDATA%\.servo` for `SERVO_CACHE_DIR`?

**Comment by larsbergstrom** [comment]
@jeandudey That sounds great to me, and much better than my other hacky ideas! The one good thing to test locally is to make sure that env vars get properly expanded when set and used by Cargo, as otherwise the files will still end up in the directory that gets cleared every time!
