### ISSUE TITLE
Use steps.Compile for `mach package` on Buildbot

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#372]
We use `./mach package -r` to [package Android APKs](https://github.com/servo/saltfs/blob/783e4f66c2fce1bc23176619b30bf7bf4133bb6c/buildbot/master/files/config/steps.yml#L56) on the android-nightly builder; the next step is then to upload the built package via S3.

Currently, the packaging step is broken (should be fixed by #290); however, even though it fails, Buildbot still tries to run the next step of uploading to S3. This is because there is no heuristic for `./mach package` and it is run as a regular `ShellCommand`.

Instead, we should add a heuristic in the `make_step` function in the `buildbot/master/files/config/factories.py` file that checks for `./mach package` and uses steps.Compile to create that step. This a) is a closer semantic match (we're "compiling" the APK), and b) will stop the build if the packaging fails, so Buildbot doesn't try the S3 upload step.

This can simply check for `package` as an argument to mach instead of using a more complicated regex as the other heuristics do, because currently there is only one type of packaging: Android APK.

**Comment by lucasloisp** [comment]
I would like to implement this. If I understand correctly, we should check that `mach_arg` re.matches "package"` and assign `step_class = steps.Compile`. Right?
I'll get to it later today

**Comment by aneeshusa** [comment]
@lucasloisp that's correct! I've assigned this to you, leave a comment if you have any questions.

Note: there are currently two copies of `make_step`, make sure to update both of them.

**Comment by jdm** [comment]
Fixed by #503.
