### ISSUE TITLE
Run nightly tests of the saltfs repo

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#376]
We should run the full saltfs suite (from scratch) on Travis every night to catch changes in upstreams (e.g. #314).

@edunham I think you like to use [nightli.es](https://nightli.es/) for this purpose? We should also have some form of alerting on failure, but I'm not sure of a good way to do that.

**Comment by edunham** [comment]
We can configure Travis to send email or IRC notifications of build status, https://docs.travis-ci.com/user/notifications/. I think emails will be the best communication channel for me. @larsbergstrom, would / where would you like notifications?

**Comment by larsbergstrom** [comment]
I agree that email is probably the best of the options. The awesomest would be automatically opening a GH issue in the case of failure, but I don't think that's an available option :-)

**Comment by aneeshusa** [comment]
Ping on this, would have helped catch #483.

**Comment by larsbergstrom** [comment]
@edunham could we use an alias on servo.org? e.g., github-saltfs@servo.org

**Comment by aneeshusa** [comment]
I opened #376 for this, but I see a few problems with this solution:
- I am unaware of any way to filter notifications by branch. Because `homu` always uses the `auto` branch, even though Travis does not send notifications for PRs this will send extra emails when going through `bors-servo`, causing lots of spam.
- Having an (internal?) email list adds more state, somewhere that is not 1) openly visible 2) likely not under version control of some kind. What does the process look like for changing that list?
- If we add this to other repos, we'd start wanting one list per repo, which is a lot of lists to keep track of (e.g. which lists am I on? did we remember to enable notifications on [new repo] yet?)

I think it may be time to invoke Zawinski's Law and add email features to homu, where we can add a few more smarts and standardize this a bit, making it available to all repos easily.

**Comment by aneeshusa** [comment]
Apparently Travis has [a new feature called Crons](https://github.com/travis-ci/beta-features/issues/1) which allows natively scheduling nightly builds. It looks like this is still in Beta but on the cusp of going GA - I believe it can be enabled through the Travis console, possibly after a support request.

I think IRC notifications would be fine to start with, although I suppose an email alias would work as well.

**Comment by edunham** [comment]
Nightly builds are now enabled and #598 adds notification in the bots channel on all builds.

**Comment by aneeshusa** [comment]
@edunham Do you know if this is working? Just got hit by a new failure (see #601), but I'm not sure if Travis ran a nightly build yesterday.

**Comment by edunham** [comment]
@aneeshusa Travis is reporting that it kicked off a cron about 15 minutes ago, which corresponds to the start time of https://travis-ci.org/servo/saltfs/builds/201652835. One can see the cron "last run" time on https://travis-ci.org/servo/saltfs/settings. According to the conversation in https://github.com/travis-ci/beta-features/issues/1, one can tell that the afforementioned build was triggered by cron because its icon by the build number looks a bit like a lego with a clock, rather than the usual icon.
