### ISSUE TITLE
Import color constant for red instead of using magic number

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#378]
Our test output is colorized for readability, and it uses ANSI escape codes to do so. The `tests/util.py` file has constants for the colors that we use. The `tests/lint/trailing_whitespace.py` test should import the RED constant from the `tests/util.py` file instead of hard-coding 31.

**Comment by aneeshusa** [comment]
There is an [open PR](https://github.com/servo/saltfs/pull/381) for this.

**Comment by KiChjang** [comment]
Previous attempt at #381.
