### ISSUE TITLE
Use OS X 10.11 on Travis

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#382]
@edunham is [switching all of our Mac builders to OS X 10.11](https://groups.google.com/forum/#!topic/mozilla.dev.servo/KWNQvd3TKPU). Because our Salt states change the underlying system in various ways, they could be affected by the specific OS version, so we should test using the same version.

In order to this, we should set the [`osx_image`](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) key in the `.travis.yml` file for any Mac builders. We'll need to set the value to either `xcode7.3` or `xcode7.2` to get OS X 10.11 - @edunham @larsbergstrom do you know which Xcode we install? (That should also get documented on the wiki.)

**Comment by vigneshsarma** [comment]
Hi, can I do this?

Only thing missing seems to be what xcode version to use. Can we go with `xcode7.3` since it is the newer one?

**Comment by aneeshusa** [comment]
Hi @vigneshsarma, unfortunately I already have a commit for this in an open PR I'm working on so this is no longer on the table! (It turns out this is a lot more involved than just adding the `osx_image` key due to rippling effects on the build, so this isn't an E-easy either). You're welcome to look at some of our other open issues though!

**Comment by aneeshusa** [comment]
Going to be fixed in #483.
