### ISSUE TITLE
Android builder is out of free space

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#397]
See the build logs from https://github.com/servo/servo/pull/11766#issuecomment-226736495 for proof.

**Comment by Ms2ger** [comment]
This is cross1; I removed some old stuff to hopefully get us in a better place right now.

**Comment by aneeshusa** [comment]
Took a look with ncdu.

A while ago, we changed the locations of various dependencies (Android SDK, NDK, etc.) on disk to better handle multiple versions and updating. `servo-linux-cross1

**Comment by aneeshusa** [comment]
I took a look with `ncdu`.

A while ago, I changed the file structure/locations of various dependencies (Android SDK, NDK, etc.) to better handle upgrades and multiple versions. `servo-linux-cross1

**Comment by aneeshusa** [comment]
I checked via Salt and `servo-linux-cross2` is also at 99%..remediating now.

**Comment by aneeshusa** [comment]
http://build.servo.org/builders/android/builds/1486 succeeded, so I went and deleted the folders. `servo-linux-cross1` has 49% usage of the primary disk and `servo-linux-cross2` has 58% of the primary disk, so we should be fine.
