### ISSUE TITLE
Handle buildbot-master OOMs better

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#406]
I just noticed that Buildbot was down and looking at the logs it seems the `buildbot-master` process was OOM killed. I've gone ahead and restarted it for now so that it is back up. If this starts happening repeatedly, we may want to give `servo-master1` more memory.

**Comment by aneeshusa** [comment]
I just saw that this happened again, seems like may not just be an intermittent problem.

**Comment by aneeshusa** [comment]
servo-master1 now has 7.5 GB of memory (up from 3.75 GB).

**Comment by larsbergstrom** [comment]
Yes, I moved this to a `m3.large` instance. It looks like the buildbot instance itself was ballooning up to > 1GB of memory usage on some very large PRs.
