### ISSUE TITLE
Remove Buildbot categories

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#412]
In #16, we added Buildbot categories, but I'm not sure if we ever used them. At this point in time, all of our builders are getting the same category value - `"auto"` - which we're not doing anything with (they can be used to filter Buildbot status targets). Additionally, the `categories` parameter [was deprecated in Buildbot 0.8.12](http://docs.buildbot.net/0.8.12/relnotes/index.html?highlight=category), the version we are running, so they are due to be removed anyways.

Files:
- buildbot/master/files/config/master.cfg

No need to add any new tests for this change.

**Comment by rozuur** [comment]
I would like to work on this as my first PR. Other than removing categories from master.cfg is there anything that needs to be done?

**Comment by aneeshusa** [comment]
@rozuur @this-jacob already has a PR open for this one! Feel free to try one of the other issues tagged `E-easy`, though.

**Comment by aneeshusa** [comment]
Fixed by #419.
