### ISSUE TITLE
Don't put the homu database in /home/servo/homu directory

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#456]
We recently deleted the main `main.db` database by accident while debugging a Homu problem; the `/home/servo/homu` directory was blown away and the database with it.

To make it harder to blow away the database inadvertently, we should put the database in a different location. I think `/var/homu/main.db` would be a good option. We also need to add a Salt state to pre-create the `/var/homu` directory with the correct permissions for Homu to use it.

Homu first needs to [land an option](https://github.com/servo/homu/issues/55) to change the `main.db` location.

Files:
- homu/files/cfg.toml
- homu/init.sls

No test necessary for now.

cc @larsbergstrom

**Comment by larsbergstrom** [comment]
Yeah, that makes sense :-)

**Comment by aneeshusa** [comment]
This has been [fixed in Homu](https://github.com/servo/homu/pull/58), so this is open for anyone to work on!

**Comment by Coder206** [comment]
@aneeshusa I'd like to help out here.

**Comment by aneeshusa** [comment]
@Coder206 It's yours, please ask if you have any questions!

**Comment by aneeshusa** [comment]
This was fixed by #476, which has been deployed. Thanks @Coder206!
