### ISSUE TITLE
Use environment variables to specify OpenSSL location on OS X

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#479]
OpenSSL is a key-only homebrew crate, and doing `brew link --force openssl` means we
```
may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
```

Instead, we need to explicitly pass the full include/lib paths to the compiler on our OS X builders, which is most easily done via environment variables.

Parts:
 - Update Salt code to no longer call `brew link --force openssl`
 - Update Buildbot configuration to pass correct values for the `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` environment variables
 - Run some command (TODO: which one?) to unlink openssl on our OS X builders

@santagada Can you give me example output for `"$(brew --prefix)"`? Does this output vary (over time, with openssl package version, randomly, with homebrew updates)? How this varies will inform how we get the right environment variables, due to the property that the Buildbot configuration is executed on the Buildbot master (a Linux machine), not the actual builder. E.g., we may lock down the OpenSSL version and template the string, or we may dynamically get the version, or just wait for the move to NSS/*ring*/crypto-library-of-your-choice-here.

Companion to servo/servo#13225.

**Comment by santagada** [comment]
I think it is pretty stable, for the general user docs I would leave the command there but for salt we can fix it to /usr/local/opt/openssl and just know that if in the future all builds on osx always fails on linking openssl is because of a more from homebrew.

**Comment by aneeshusa** [comment]
@santagada Due to how Buildbot works, it's much easier to set static environment variables than dynamic ones (i.e. those that shell out, which is the `"$(brew --prefix openssl)"` part). Is the output of that command always `/usr/local/opt/openssl`, or does it change based on the openssl version?

**Comment by aneeshusa** [comment]
OK, from IRC it sounds like the output of that command should always be `/usr/local/opt/openssl`, so we can hardcode the environment variable values for now. @santagada, you were interested in this so I'll assign this to you.

Files to change:
  - `servo-build-dependencies/init.sls`: Remove the salt state which runs `brew link --force openssl`
  - `buildbot/master/files/config/environments.py`: Add the new environment variables to the `build_mac` `Environment`.

Tests:
  - No tests needed (aside from getting a successful build).

We also need to somehow "unlink" openssl on our existing builders, so if you know a command for that we can run it by hand.

**Comment by aneeshusa** [comment]
@santagada I actually have taken care of this in #483, as part of upgrading Homebrew to 1.0.0. Feel free to work on another issue, and thanks again for your initial report and PR to make our OpenSSL usage via Homebrew better!

**Comment by santagada** [comment]
I'm on vacation, sorry for not unassining myself, and thanks for fixing this
