### ISSUE TITLE
Open ports for mosh in firewall

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#507]
Mosh is [now installed](https://github.com/servo/saltfs/pull/335) on our machines, but it requires UDP ports 60000-61000 to be opened. (It starts allocating ports per connection at 60000 and goes up, so we can also open fewer ports, e.g. 60000 - 60010).

I believe these are currently being filtered by the AWS network infrastructure (not iptables). Would it be possible to open these ports so mosh can be used?

**Comment by aneeshusa** [comment]
cc @edunham

**Comment by edunham** [comment]
AWS is now set to allow UDP 60000-61000 on servo-master.

**Comment by aneeshusa** [comment]
Thanks! `mosh` is installed on all of the machines, so can you open those ports on the builders as well?

**Comment by edunham** [comment]
Opened on the builders for now; eventually I'd like to switch to a model of accessing everything through a bastion host with better logging and detection of unusual access.
