### ISSUE TITLE
Buildbot no longer exposes the logs from multiple test jobs

### ISSUE THREAD

**Issue by Ms2ger** [servo/saltfs#524]
http://build.servo.org/builders/linux-rel-wpt/builds/468 has three test jobs, but all links point to the log for the first one.

**Comment by aneeshusa** [comment]
I've identified this as a bug in the new dynamic step creator and am working on a PR for this.

**Comment by aneeshusa** [comment]
FYI there were some fixups required (#526, #528), but this seems to be working properly now.
