### ISSUE TITLE
Homebrew nightly build not updated anymore (since 26)

### ISSUE THREAD

**Issue by paulrouget** [servo/saltfs#532]
Last update was on the 26th of October: https://github.com/servo/homebrew-servo

Does `./etc/ci/update_brew.sh` still run?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/etc/ci/buildbot_steps.yml#L29 says it should be.

**Comment by aneeshusa** [comment]
It seems that the `TOKEN` variable is unbound: http://build.servo.org/builders/mac-nightly/builds/129/steps/shell__3/logs/stdio, causing the upload to fail.

Will investigate further after class.

**Comment by aneeshusa** [comment]
Reopening until `mac-nightly` runs again tonight and I can confirm that this is working again.

**Comment by aneeshusa** [comment]
@larsbergstrom started a force build and this is working again: https://github.com/servo/homebrew-servo/commit/3ec0ce011547f41f5854177427508c087ea4533a.
