### ISSUE TITLE
Homebrew nightly build not updated anymore (since 11/4)

### ISSUE THREAD

**Issue by paulrouget** [servo/saltfs#535]
```
./etc/ci/update_brew.sh
 in dir /Users/servo/buildbot/slave/mac-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./etc/ci/update_brew.sh']
 using PTY: False
ls: target/brew/servo-????-??-??.tar.gz: No such file or directory
program finished with exit code 1
elapsedTime=0.017824
```

**Comment by aneeshusa** [comment]
Probably due to https://github.com/servo/servo/pull/14058, will investigate later.

**Comment by paulrouget** [comment]
@aneeshusa anything I can do to help?

**Comment by paulrouget** [comment]
Now that `etc/ci/upload_nightly.sh` creates the timestamp, how can `update_brew.sh` know the proper url for that package?

I see 3 options:

1. in upload_nightly, store the timestamp somewhere for re-use in update_brew.sh
2. call update_brew from upload_nightly, not from buildbot_step
3. put together the timestamp earlier and store it in a shared env variable

**Comment by aneeshusa** [comment]
Sorry about the delay, that's indeed the root of the issue; I think option 2 is the best remediation.
