### ISSUE TITLE
linux builders need CA cert updated

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#540]
18:45:24 <@Manishearth> edunham: I think our linux buildslaves need their root cert store updated
 18:45:34 <@Manishearth> they can't handle letsencrypt
 18:45:40 <@Manishearth> (https://joshmatthews.net)
 18:45:51 <@Manishearth> so python urllib2.urlopen or requests.get throws an error

**Comment by Manishearth** [comment]
Working with an upgraded `requests` lib I get a better error message, linking me to https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

```
>>> import requests
>>> requests.get("https://www.joshmatthews.net/intermittent-tracker/query.py?name=private")
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
```

A quick fix is to turn off SSL verification. The distro does not have an updated version of python available; but we could try using python3 for mach.

**Comment by edunham** [comment]
https://github.com/servo/saltfs/pull/542 should fix, thanks @Manishearth for figuring out what was up :)
