### ISSUE TITLE
Run intermittent-tracker on servo-master1

### ISSUE THREAD

**Issue by Manishearth** [servo/saltfs#543]
We should run https://github.com/servo/intermittent-tracker on servo-master1

(Playing around with it now to get it to work)

This needs `github3.py==1.0.0a4` installed.

(Working out the other dependencies)

**Comment by jdm** [comment]
github3.py is only necessary for running `sync.py`. You can also run that locally, pipe the output to `intermittents.json` and scp the json file to the builder.

**Comment by jdm** [comment]
(Note that for best results the JSON file should be created right before enabling the webhook)

**Comment by Manishearth** [comment]
I've got a version running with flask at http://build.servo.org/intermittent-tracker/query.py?name=private

(CGI seemed like a whole other world of pain, whereas we already use bottle in homu and it's the same principle here)

**Comment by Manishearth** [comment]
https://github.com/servo/intermittent-tracker/pull/1 has the flaskification.

The virtualenv needs flask installed. github3 doesn't get installed in non-root mode because of openssl stuff in the cryptography lib 🙁 

We will need it eventually for a startup task to populate the db. We should also start verifying webhook secrets.

@aneeshusa Any idea how to daemonize this?

**Comment by Manishearth** [comment]
I deployed a cherry-picked version of this (to avoid the android issue), cc @larsbergstrom 

It works.
