### ISSUE TITLE
We're gating on Android

### ISSUE THREAD

**Issue by Ms2ger** [servo/saltfs#545]
Somehow #539 got deployed before its time.

On `servo-master1`, I cloned 70fe5103dd9846cf5859dc48e8add5fcb73c9c2f into `/tmp/salt-testing-root/saltfs` and ran `salt 'servo-master1' state.highstate 2>&1`. Waiting to see if that helped.

**Comment by Ms2ger** [comment]
CC @aneeshusa @larsbergstrom @metajack @Manishearth

**Comment by Ms2ger** [comment]
CC @edunham

**Comment by Ms2ger** [comment]
That seems to have helped as a temporary band-aid.

Some notes for the post-mortem:
* I didn't find docs on how saltfs code is deployed now; if that had existed I could probably have reverted in the repo and followed the docs
* https://github.com/servo/servo/wiki/Buildbot-administration still mentions /srv/salt/, which no longer exists
* We landed https://github.com/servo/saltfs/pull/539 before we were able to deploy it, putting saltfs master in a known-bad state
* There is no log of deploys (that I could find), which would have made it easier to verify that a bad deploy had happened
* There is no obvious / documented way to revert a deployment
* The changes were deployed, apparently without someone watching that everything still worked after
* No issue was filed when the problem was first discovered

**Comment by Manishearth** [comment]
Bad deploy was mine; I was testing out the intermittent tracker stuff. It's much harder to deploy from branch now, though.

**Comment by larsbergstrom** [comment]
It's my fault for landing the Android gating assuming it would be "ready to go shortly" and then taking forever to get mozjs building on Android.

We do try to log (see https://github.com/servo/servo/wiki/Buildbot-administration#applying-changes), but there's no default verbose / logged mode for salt highstates, at least that I know how to turn on. It's something we've definitely wanted!

**Comment by aneeshusa** [comment]
#549 covers documentation, and #437 tracks logging, which is addressed by #547. We're still gating on Android but recent builds are all green, so I'm closing this.
