### ISSUE TITLE
upload_nightly.sh: git error

### ISSUE THREAD

**Issue by paulrouget** [servo/saltfs#575]
See: http://build.servo.org/builders/mac-nightly/builds/200/steps/shell__2/logs/stdio

I requires a valid email address, and `servo@servo-mac2.(none)` is not.

I see 3 options:

- set the domain name of the machine then it doesn't return `(none)`
- set an email address under `common/init.sls`. Would it work to just add a `email` field under `servo:user.present:`?
- user `--author` when commiting

/cc @aneeshusa

**Comment by aneeshusa** [comment]
IMO option 3 is best; I'm thinking `'Tom Servo <servo@servo.org>'` as the author.

We should also be configuring the domain name on the builders, but Salting the macOS machines is currently broken.
