### ISSUE TITLE
GITHUB_HOMEBREW_TOKEN: unbound variable

### ISSUE THREAD

**Issue by paulrouget** [servo/saltfs#576]
See: http://build.servo.org/builders/mac-nightly/builds/201/steps/shell__2/logs/stdio

I'm not sure to understand why it's not working.

/cc @aneeshusa

**Comment by aneeshusa** [comment]
I checked on the buildmaster and it looks like #541 has been deployed, but we're hitting #552 again - the `factories.py` file is from January 4th, but the `factories.pyc` file is from December 22nd. This is causing the token to not get passed correctly.

@larsbergstrom is just removing the `.pyc` files OK, or is a full restart of Buildbot required?

Note that #505 should fix #552 in the future.

**Comment by larsbergstrom** [comment]
@aneeshusa You will need to both remove the `.pyc` files and restart Buildbot to pick up the changes to the `.py` files.

**Comment by aneeshusa** [comment]
I removed the `.pyc` files and restarted Buildbot yesterday; this is now working: http://build.servo.org/builders/mac-nightly/builds/208.

I also mentioned that info in the wiki for now.
