### ISSUE TITLE
Add test to check all repos in Homu's cfg.toml are valid

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#581]
This will prevent typos in repo names as well as issues like #580.

Files:
- Make a new test file `tests/sls/homu/valid_repos.py`

The test should read the deployed `cfg.toml` file for Homu (should be at `/home/servo/homu/cfg.toml`) using the `toml` Python library. Each subkey under the `repo` key of the configuration should be queried for existence on GitHub as a valid repo.

Bonus points if you query the GitHub API for the webhooks of each repo to check that an appropriate webhook is set up (see https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu), although I think this might require an new access token with permissions we don't necessarily want to provide.

**Comment by aneeshusa** [comment]
This can be tested locally using the `servo-master1` VM [in Vagrant](https://github.com/servo/saltfs/blob/master/docs/salt.md#testing-with-vagrant); look at other tests under `tests/sls/homu` for similar examples that read the deployed configuration.

**Comment by aneeshusa** [comment]
It looks like we'd need the `read:repo_hook`, which only allows read and ping abilities for webhooks on public and private repos, per [the GitHub v3 API docs](https://developer.github.com/v3/oauth/). I think this is a reasonably small scope to provide to Travis to integrated into CI, since Travis already knows our webhook secret.

**Comment by rwaweber** [comment]
Hey @aneeshusa, I think I may give this a shot tonight. 

Also, mentioned it in #servo, but since I had a tough time grabbing the dependencies (at least on El Capitan) for the vagrant environment, I setup this cask: https://github.com/rwaweber/homebrew-servo-saltfs.

**Comment by aneeshusa** [comment]
Great @rwaweber, ask if you have any questions.

BTW, did you try installing Vagrant 1.8.1 from [the Hashicorp releases](https://releases.hashicorp.com/vagrant/) or via [an older Cask URL](https://github.com/caskroom/homebrew-cask/blob/b43b81d80661f38b6fe94c3f6262c862942d6fb3/Casks/vagrant.rb) (at least, I think you can do `brew cask install <some_url>`...)?

**Comment by rwaweber** [comment]
I've got a WIP [here](https://github.com/servo/saltfs/pull/606).

A couple things:
1. I'm assuming that its not desired to track the differences from the servo org to the home configs, since there are a number of deprecated repos that are unlikely to be removed. Just from my own thinking, this would yield minimal usefulness; mainly something that I came up with while logic-ing it out. I would be happy to remove this functionality to more closely address the initial request.
2. Just making sure that I'm not breaking anything, since I'm only developing with the single `servo-master1` machine, it shouldn't be able to retrieve the builders. This [error](https://gist.github.com/rwaweber/54cb3cb46245666d6d5ffad208fb0059) was what I was getting and led me to that conclusion. 
3. I'm open to a different means than importing requests to query github for repos to avoid adding another dependency.

**Comment by rwaweber** [comment]
Pagination is configured, though I ended up rate-limiting myself a couple times during testing. As a result, I implemented a check for a token variable to allow for authenticated requests. I could imagine that being ratelimited by the github api would be less than ideal :sweat_smile: 

Not sure what the best means of retrieving that could be, maybe yanking from pillar?

I still need to spend some time thinking about the webhook bit as well.

**Comment by jdm** [comment]
@aneeshusa Ping to reply to the previous question.

**Comment by rwaweber** [comment]
Spent a bit of time investigating the webhook check, and the [earlier](https://github.com/servo/saltfs/issues/581#issue-202403929) assumptions are [correct](https://developer.github.com/v3/orgs/hooks/#scopes--restrictions) that it would be necessary to issue an auth token with elevated access.

Also, poking around some of the configurations, I noticed that there's a line in the `cfg.toml` at `/home/servo/homu/` that seems to be referring to a "TEST_HOMU_GH_ACCESS_TOKEN". Is there a way that I would be able to refer to that value in these tests like I attempted to do [here](https://github.com/servo/saltfs/pull/606/files#diff-15dac4232067fee18d88f2c99ffd56bcR38)?

**Comment by rwaweber** [comment]
We determined that a Get request to each repo url was sufficient and ultimately didn't warrant an access token.
I think that this could probably be closed now, right?

**Comment by aneeshusa** [comment]
Yep, this can be closed for now. We can open another issue for the bonus points task at another time if that becomes necessary.
