### ISSUE TITLE
Windows buildbot failure: LLVM ERROR: IO failure on output stream.

### ISSUE THREAD

**Issue by Ms2ger** [servo/saltfs#585]
http://build.servo.org/builders/windows-msvc-dev/builds/482/steps/compile__1/logs/stdio

Possibly running out of disk space?

**Comment by Ms2ger** [comment]
I hit the "graceful shutdown" button on `servo-windows1`, that seems to have helped a bit.

**Comment by Ms2ger** [comment]
@edunham @larsbergstrom this is making windows the long pole, can we please get a real fix? Thanks!

**Comment by aneeshusa** [comment]
I just logged into `servo-windows1` and restarted Buildbot, as well as removed some obsolete build directories. Currently looking for more old files to delete to free up space, but this should be ok for now.
