### ISSUE TITLE
Add a third linux-cross build machine

### ISSUE THREAD

**Issue by mbrubeck** [servo/saltfs#588]
Android and Linux ARM builds have become a frequent bottleneck in Servo's buildbot capacity.  Adding a third buildslave to run these jobs would let them run in parallel, reducing the total turnaround time.  CC @larsbergstrom and @edunham.

**Comment by edunham** [comment]
http://build.servo.org/buildslaves/servo-linux3

**Comment by edunham** [comment]
Final highstate of the buildmaster will alert Buildbot to the new slave

**Comment by aneeshusa** [comment]
Still not working, see #643.

**Comment by aneeshusa** [comment]
#643 has been rolled out and Buildbot now recognizes the third cross builder: http://build.servo.org/buildslaves
