### ISSUE TITLE
Make `pip.installed` actually upgrade Homu

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#593]
It seems like the `pip.installed` state currently is failing to update Homu to newer versions when the git revision changes, requiring manual upgrades.

Temporary manual upgrade procedure:
- Stop Homu with `service homu stop`
- Back up the Homu database (currently located at `/home/servo/homu/main.db`)
- Blow away the Homu dir (`/home/servo/homu`)
- Run the Salt highstate to install the upgraded Homu
- Replace the Homu database

**Comment by jdm** [comment]
This also affects the version of https://github.com/servo/intermittent-tracker/ that's in use; it seems like the only steps necessary there would be:
* Blow away the Homu dir (/home/servo/intermittent-tracker)
* Run the Salt highstate to install the upgraded intermittent-tracker

**Comment by aneeshusa** [comment]
I haven't checked, but I think #623 may have fixed this.

**Comment by jdm** [comment]
Pip installs fine from git sources when using the `--upgrade` flag. Adding the equivalent flag in salt makes this work.

**Comment by jdm** [comment]
#623 definitely should have fixed this.
