### ISSUE TITLE
Deploy servo-gecko-try

### ISSUE THREAD

**Issue by Manishearth** [servo/saltfs#619]
https://github.com/Manishearth/servo-gecko-try

Needs a similar setup as the intermittents tracker as far as flask is concerned

The setup is a bit trickier. You need a servo clone, and hg clones of https://hg.mozilla.org/mozilla-central/ and https://hg.mozilla.org/integration/autoland/ somewhere (preferably as child dirs). Additionally, you need a clone of http://hg.mozilla.org/hgcustom/version-control-tools/ somewhere, probably in `~/.mozbuild/version-control-tools`. We need a public/private keypair that's tied to L1 managed by salt somewhere too (bug filed for getting the key and username: https://bugzilla.mozilla.org/show_bug.cgi?id=1347259).

Either the global hgrc (`~/.hgrc`) or each of the local hgrcs (`.hg/hgrc`) in the two firefox clones need to have these lines in them:

```rc
[extensions]
mq =
push-to-try = ~/.mozbuild/version-control-tools/hgext/push-to-try

[ui]
username = Bors <whatever@whatever.com>
ssh = ssh -l 'borsusername@bors.com' -i '/path/to/key.pub'
```

The [config file](https://github.com/Manishearth/servo-gecko-try/blob/master/config.json.example#L1) should point to all the clones. `host` should probably be 127.0.0.1 if this service will be talked to by homu (and not open to the web).

cc @edunham

**Comment by larsbergstrom** [comment]
I suspect that we would like this to live on a server that is not the one with Homu on it, as that machine will be pretty locked-down, relative to the rest of Servo's infrastructure.

**Comment by edunham** [comment]
@Manishearth does the `[ui]` section of that `.hgrc` ever do anything? Specifically, should we point it at some usually-ignored `@servo.org` email in case anything we care about would get annoyed at the mail bouncing?

**Comment by Manishearth** [comment]
The username exists for commit authoring. The `ssh` is there for the right pubkey and username to be used.

**Comment by edunham** [comment]
initial work at https://github.com/servo/saltfs/pull/700 which will probably break and need some fixups.

**Comment by aneeshusa** [comment]
See also Manishearth/servo-gecko-try#3 for some things I'd like to see done before putting this into production. Some of the upcoming changes should make this easier to deploy on the Salt side (app does all repo juggling by itself, publishing to PyPi instead of using git dependency, etc.)

**Comment by edunham** [comment]
VCS sync is no longer.
