### ISSUE TITLE
Windows builder may be out of disk space

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#636]
#16472 received this error:
```
LLVM ERROR: IO failure on output stream.
error: Could not compile `script`.
```

**Comment by aneeshusa** [comment]
I removed the build directories for the various `windows-gnu` builds; `servo-windows1` now has ~10GB free and `servo-windows2` has ~37GB free, which should be enough to get builds running again.

I'm working on a PR to automatically clean old rust and cargo nightlies, which should help manage this in the future.

**Comment by aneeshusa** [comment]
The PR is up at servo/servo#16487. Closing this for now as the Windows builders have some headroom for builds.
