### ISSUE TITLE
Uninstall MinGW and MSYS on Windows builders to reclaim disk space

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#640]
servo/servo#16487 automatically cleans out old MSVC rustc and cargo nightlies, but we have ~20GB of old MSYS rustc and cargo nightlies on the Windows builders that won't get automatically removed.

@larsbergstrom or @metajack, now that we're not supporting MinGW/MSYS could one of you please uninstall them on the builders and purge out the `C:\msys64` folder holding the old nightlies?

**Comment by metajack** [comment]
Just needs to happen on servo-windows1 and servo-windows2?

**Comment by aneeshusa** [comment]
Yes, those are the only 2 windows builders AFAIK.

**Comment by metajack** [comment]
This is done.

**Comment by larsbergstrom** [comment]
Wait, I thought we're still supporting MinGW/MSYS for Tor builds of Firefox that include Servo? i.e., we wouldn't test or release the bits, but we'd still ensure Servo builds on it.

**Comment by aneeshusa** [comment]
See also #620, where we stopping running `windows-gnu` builds on Windows.

**Comment by larsbergstrom** [comment]
oh, it looks like @metajack decided to go forward with it - I missed that mail to the thread:
https://github.com/servo/saltfs/issues/640#issuecomment-296273105

I'd propose just reinstalling the tools until we can rewrite the script.
