### ISSUE TITLE
Enable Travis Auto Cancellation

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#646]
This is a new beta feature:  https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

When iterating on a branch and force pushing frequently, this will automatically cancel old builds that haven't yet started to avoid running builds which would have stale results.

cc @edunham @larsbergstrom @metajack

**Comment by larsbergstrom** [comment]
That sounds great! Do you think we should enable it on all of our repos? It looks like it's a per-project setting.

**Comment by metajack** [comment]
I think we should enable the PR auto-cancel but not the branch auto-cancel. That way we'll still know which specific commit introduced a failure. I've enabled PR auto-cancel for most of the repos in the servo org. I wish there was a way to control this more easily than clicking into every repo on Travis CI and then hitting settings and flipping the toggle.

**Comment by aneeshusa** [comment]
@metajack In their [beta issue tracker](https://github.com/travis-ci/beta-features/issues/8), the Travis CI folks mention this can be modified via the API. I think it might be nice to make a script for this (similar to the ones in #457).

**Comment by aneeshusa** [comment]
In the meantime, it might be nice to add this to the checklist for [adding new repos](https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu) on the wiki.

**Comment by metajack** [comment]
Make the wiki changes.

**Comment by aneeshusa** [comment]
This is enabled and documented, so I don't see any other action items for this right now. Closing.
