### ISSUE TITLE
Enable choosing specific build machine for Buildbot force builds

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#658]
We need to add the `BuildslaveChoiceParameter` to our `ForceScheduler`s.
docs: https://docs.buildbot.net/0.8.12/manual/cfg-schedulers.html#buildslavechoiceparameter

**Comment by edunham** [comment]
@aneeshusa, have you re-highstated the buildmaster to deploy this?

**Comment by aneeshusa** [comment]
@edunham Not yet, there are builds in the queue: http://build.servo.org/homu/queue/all

I also made a new label (S-needs-deploy) to help keep track of this in the future.

**Comment by edunham** [comment]
Thank you!
