### ISSUE TITLE
Run highfive on `servo-master1`?

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#662]
Implementing https://github.com/servo/highfive/issues/179 will require some Servo-specific configuration so Highfive knows to add the S-needs-deploy label to merged PRs. I'd like to keep configuration bits under version control as much as possible.

Does it make sense to Salt our highfive instance and run it on servo-master1?

cc @jdm @larsbergstrom @edunham

**Comment by jdm** [comment]
The configuration bits go in the highfive repository right now. I don't see a need to move this to the builders yet.

**Comment by jdm** [comment]
Prior art: https://github.com/servo/highfive/blob/master/collaborators.ini

**Comment by aneeshusa** [comment]
Aha, I saw only `config.sample`, that makes more sense. Closing.
