### ISSUE TITLE
servo-linux-cross2 is having trouble building arm64

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#683]
```
--- stderr
configure: error: in `/home/servo/buildbot/slave/arm64/build/target/release/build/backtrace-sys-204dc57c91e9a514/out':
configure: error: C compiler cannot create executables
See `config.log' for more details.
thread 'main' panicked at 'failed with: exit code: 77', /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.11/build.rs:136
```

**Comment by jdm** [comment]
Haven't seen this for a long time.

**Comment by jdm** [comment]
Saw this again on servo-linux-cross1 today in https://github.com/servo/servo/pull/18821.

**Comment by SimonSapin** [comment]
This happened for both arm32 and arm64 in https://github.com/servo/servo/pull/18821, both times on servo-linux-cross1.

**Comment by jdm** [comment]
Both arm32 and arm64 failed both times, and across all of servo-linux-cross1, servo-linux-cross2, and servo-linux-cross3. I wish I could get ahold of the config.log files that were generated for those builds :(

**Comment by jdm** [comment]
```
configure:2977: checking for C compiler default output file name
configure:2999: aarch64-linux-gnu-gcc -O3 -ffunction-sections -fdata-sections -fPIC -m64   conftest.c  >&5
aarch64-linux-gnu-gcc: error: unrecognized command line option '-m64'
```

**Comment by jdm** [comment]
Accordingly, the two configure scripts are invoked slightly differently:
Failed:
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.11/src/libbacktrace/configure --with-pic --disable-multilib --disable-shared --disable-host-shared --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu

Successful:
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.11/src/libbacktrace/configure --with-pic --disable-multilib --disable-shared --disable-host-shared --host=aarch64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu

**Comment by jdm** [comment]
Cargo is definitely building backtrace-sys with an unexpected target, according to this output:
```
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("aarch64-linux-gnu-gcc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
```

**Comment by SimonSapin** [comment]
CC @alexcrichton, in case you’ve seen this before or have some idea what’s going on.

**Comment by jdm** [comment]
Well, either it's an unexpected target, or it's expected but cc-rs is finding the wrong compiler for it (perhaps we're setting CC somehow before the backtrace-rs build script is invoked?).

**Comment by jdm** [comment]
Ok, so the compiler is being set to the cross binary by the build environment in https://github.com/servo/saltfs/blob/df07d3ace136a1c4594042af659f8584ba59e8fb/buildbot/master/files/config/environments.py#L113-L144 . That's why we see an issue when Cargo builds backtrace with a non-cross target. The mystery remains as to why that's happening - any suggestions for how to figure that out @alexchrichton?

**Comment by jdm** [comment]
Oh, I know why this is hitting us on https://github.com/servo/servo/pull/18821 - the new version of metadeps uses error-chain 0.10, which depends on backtrace. dbus and x11-rs both have a build dependency on metadeps, which means that we now compile backtrace for the host system, leading to the situation where we end up selecting the wrong compiler.

**Comment by alexcrichton** [comment]
Interesting! Perhaps this is a case where the env var should be `CC_arm-linux-gnueabihf-gcc` instead of just `CC`?

**Comment by jdm** [comment]
That sounds like a good solution; thanks!
