### ISSUE TITLE
add gecko build to perf.rust-lang.org

### ISSUE THREAD

**Issue by metajack** [servo/saltfs#712]
We should have the Gecko rust bits in Rust's compiler performance tracking infrastructure.

**Comment by metajack** [comment]
cc @larsbergstrom @jonathandturner @Manishearth

**Comment by jonathandturner** [comment]
Any blockers for this?

**Comment by SimonSapin** [comment]
Fixed in https://github.com/rust-lang-nursery/rustc-perf/pull/162.
