### ISSUE TITLE
Add Homu, Travis, etc to servo/gecko-media

### ISSUE THREAD

**Issue by nox** [servo/saltfs#718]
Cc @larsbergstrom

**Comment by larsbergstrom** [comment]
cc @edunham

**Comment by edunham** [comment]
https://github.com/servo/gecko-media/pull/10

**Comment by edunham** [comment]
Flipped the switch on the Travis side, so once the .travis.yml lands it'll build at the usual times

**Comment by aneeshusa** [comment]
`.travis.yml` has landed in the repo and [Homu is enabled](https://github.com/servo/saltfs/pull/736), so AFAIK this is done. Closing.
