### ISSUE TITLE
servo-mac5, servo-mac6, servo-mac8, and servo-mac9 only have 4gb of RAM

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#731]
This is causing confusing OOM problems like https://github.com/servo/servo/issues/18806.

**Comment by jdm** [comment]
@edunham What specs are the machines expected to have?

**Comment by jdm** [comment]
I ran `shutdown -h now` on it so there's no chance we accidentally start using again.

**Comment by jdm** [comment]
I have not shut down servo-mac5 yet because it is running builds, but top shows `PhysMem: 3508M used (855M wired), 586M unused`.

**Comment by jdm** [comment]
Same story for servo-mac8.

**Comment by jdm** [comment]
And for servo-mac9!

**Comment by jdm** [comment]
All the remaining machines either have 16gb or 8gb of ram.

**Comment by aneeshusa** [comment]
I checked `salt '*' grains.get mem_total` which will show RAM for each machine. It looks like all the Linux and Windows machines have at least 7.5 GB of RAM (`servo-linux{1,2,3}` each have 30GB!), so they should be OK.

**Comment by edunham** [comment]
mac5: https://portal.macstadium.com/tickets/40138

mac6: https://portal.macstadium.com/tickets/40139

mac8: https://portal.macstadium.com/tickets/40140

mac9: https://portal.macstadium.com/tickets/40141

**Comment by aneeshusa** [comment]
The MacStadium tickets have been resolved and I rechecked via the same Salt command; all Macs now have 16GB of RAM, except for `servo-mac1` and `servo-mac7`, which have 8GB each. Closing this.
