### ISSUE TITLE
add an android cargo builder

### ISSUE THREAD

**Issue by metajack** [servo/saltfs#76]
We want some deps checked on android, but need a special cargo builder for that. There is already some work done in master.cfg so that specific projects can opt into android builds (ie, `ANDROID_PROJECTS`).

I think good candidates are any of the `*-sys` and their bindings: skia, rust-azure, mozjs, rust-mozjs, libfontconfig, etc. These were recently broken on android when trying to modify them for desktop arm linux systems. Some basic build checking would have prevented that bustage.

**Comment by larsbergstrom** [comment]
We're no longer doing Cargo builds.
