### ISSUE TITLE
Install rustup.rs on Windows builders

### ISSUE THREAD

**Issue by SimonSapin** [servo/saltfs#773]
https://github.com/servo/saltfs/pull/758 works for Mac and Linux. On Windows we need to download `https://win.rustup.rs/` and run it as `rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain none`.

@aneeshusa, could you help with this?

**Comment by larsbergstrom** [comment]
@edunham @aneeshusa Are we at a point right now where we should be able to download and install stuff on windows via salt? Or is it still somewhat manual setup? I didn't see any other steps on the machines.

I was looking at the instructions and we seem to have lost all the tips on how to install buildbot, etc. on the Windows machine, so I'm not too sure that it's in anything other than a manual place right now, but didn't want to log in and follow Simon's steps w/o checking.

**Comment by jdm** [comment]
This is actually a good point; I have never seen a highstate actually run on the windows machines. There's always a problem communicating with them, which is why I never noticed that installing rustup from salt on windows would not work.

**Comment by larsbergstrom** [comment]
It appears an installation has already been done, as running the above command resulted in `info: skipping toolchain installation` on both machines.

**Comment by SimonSapin** [comment]
That output is expected when installing with `--default-toolchain none`. And `salt -E 'servo-windows*' cmd.run "C:\Users\Administrator\.cargo\bin\rustup.exe -V"` does work now, the file did not exist before. Thanks!

**Comment by aneeshusa** [comment]
@larsbergstrom #785 will fix highstating on Windows.

 There are Salt installation docs [in-tree](https://github.com/servo/saltfs/blob/bcdbe98ecc9c6c57ef9a584af4db14713604c653/docs/salt.md#windows), and the [wiki links](https://github.com/servo/servo/wiki/Buildbot-administration#dealing-with-troubles) to the upstream docs for [running Buildbot on Windows](http://trac.buildbot.net/wiki/RunningBuildbotOnWindows). Issue #302 also has some information about setting up Buildbot on Windows.
