### ISSUE TITLE
Remove travis gating from webrender repo.

### ISSUE THREAD

**Issue by glennw** [servo/saltfs#803]
Removing travis integration altogether would be fine, if that won't break any of the current setup (additional reviewers etc).

**Comment by jdm** [comment]
There is no config related to travis for webrender in our homu config anymore. You'll need to get someone with admin powers (like jack or lars) or disable the travisci integration.

**Comment by glennw** [comment]
@jdm I opened this bug based on a request from @edunham and @larsbergstrom to have a github issue...

**Comment by larsbergstrom** [comment]
@jdm I believe there is still travis info for webrender here:
https://github.com/servo/saltfs/blob/master/homu/files/cfg.toml#L92-L94

The work is to:
1) Remove those lines
2) Ensure that the additional reviewers are still present through manual addition elsewhere in the file.
