### ISSUE TITLE
Update all Macs to 10.11

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#811]
Pulled out of #725; I just checked and these 4 macs are still on 10.10.5.

With the resolution of #731, 5/9 Mac builders now have macOS 10.11.6, so I think for now it'll be easiest to get all the Macs on 10.11.6 and think about upgrading to 10.12 later. Macs that still need to be upgraded:
- [ ] servo-mac2
- [x] servo-mac3
- [x] servo-mac4
- [x] servo-mac7

I also looked at the `sw_vers` output and it looks like most of the 10.11.6 Macs are on `Build Version 15G1611`. I'm not sure if this matters, but extra consistency here can't hurt.

@larsbergstrom or @edunham Can you put in tickets with MacStadium to upgrade the remaining Macs as well?

**Comment by edunham** [comment]
I've recently learned from Macstadium that we can get them to clone one mac's image onto another, which is looking like a far more time-efficient way to get the busted ones set up. I'm figuring that we should dup mac1 onto mac3 to start with, since mac3 has been broken awhile, and then verify that only updating thehostname and minion ID, and re-generating the Salt key and accepting it in the master, are required to get a clone into working order. I'm filing the ticket to do that today.

**Comment by edunham** [comment]
Update: Request filed to clone 1 onto 3 and leave 3 powered off. Hopefully by the time I get in tomorrow, I will have a clean new mac3 matching mac1's config, in which I can: 
- [ ] nuke old buildbot logs
- [ ] update hostname
- [ ] update buildslave id
- [ ] regen key
- [ ] accept new key in salt master

and at that point it should come back into rotation. After debugging this process, I'll repeat it on the other hosts that are broken or need updates.

**Comment by SimonSapin** [comment]
Updating to today’s Nightly seems to be blocked on this (or finding another work-around): https://github.com/servo/servo/pull/21089#issuecomment-399749966. It appears to be a miscompilation that only occurs in release mode on macos 10.10 (not 10.11). I haven’t managed to run lldb on servo-mac2 (`error: process exited with status -1 (unable to attach)`).

Any help would be appreciated (either with debugging or with pushing the upgrade forward).

**Comment by SimonSapin** [comment]
Thanks to heroic work by kennytm in https://github.com/rust-lang/rust/pull/51828, the linker bug is worked around and this macOS upgrade is no longer blocking compiler upgrades: https://github.com/servo/servo/pull/21089 has landed. (It’d still be good to do of course.)

**Comment by jdm** [comment]
salt-mac4 has been upgraded to 10.13.

**Comment by jdm** [comment]
salt-mac7 has been upgrade to 10.13.

**Comment by SimonSapin** [comment]
This appears to be done, everything is on 10.11.6 now. (Not 10.13, somehow.)

```sh
$ for i in $(seq 9); (echo -n "servo-mac$i "; ssh servo-mac$i.servo.org sw_vers|grep ProductVersion)
servo-mac1	ProductVersion:	10.11.6
servo-mac2	ProductVersion:	10.11.6
servo-mac3	ProductVersion:	10.11.6
servo-mac4	ProductVersion:	10.11.6
servo-mac5	ProductVersion:	10.11.6
servo-mac6	ProductVersion:	10.11.6
servo-mac7	ProductVersion:	10.11.6
servo-mac8	ProductVersion:	10.11.6
servo-mac9	ProductVersion:	10.11.6
