### ISSUE TITLE
Missing ANDROID_NDK environment variable is busting all android builds

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#869]
https://github.com/servo/saltfs/commit/f36daa1822f43230f311c3c1e21aeae8578faf88#diff-990e5bffeb54ff05fc733688c3a0d4e4L108 has broken the check_dynamic_symbols part of the android build: http://build.servo.org/builders/android/builds/12019/steps/shell__5/logs/stdio . I've also deleted the directory that it pointed to on each of the builders, so we can't just restore the value as-is.

cc @Manishearth

**Comment by Manishearth** [comment]
TIL you can close github issues across repos
