### ISSUE TITLE
make_user_data is silly

### ISSUE THREAD

**Issue by Ms2ger** [servo/saltfs#99]
Could use `""" """`-style strings.

**Comment by rilut** [comment]
@Ms2ger do this need help? May I do it?

**Comment by Ms2ger** [comment]
Go for it! The code is at <https://github.com/servo/saltfs/blob/54a23126c819ddcbfccbee4a3289d31df8bc852d/buildbot/master/master.cfg#L35>; it should be a single multiline string, using python's string formatting (`%s`) to fill in the keys.

**Comment by aneeshusa** [comment]
This can be closed since #164 is merged.
